---
- name: Fuse Undeploy Bundles Playbook
  hosts: fuse-lab-environment
  remote_user: root
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    # Undeploying Bundles in Two Fuse Standalone
    - { role: fuse-undeploy-bundle, esb_name: 'esb01' }
    - { role: fuse-undeploy-bundle, esb_name: 'esb02' }
